# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slplotpolygon <- function(plotinitres, lon, lat, colfill = "black", colborder = "black", borderlwd = 0.01, borderlty = 1L, ignorevisibility = FALSE, removeidenticalneighbours = TRUE, refineboundary = TRUE, refineboundaryprecision = 1) {
    invisible(.Call(spheRlab_slplotpolygon, plotinitres, lon, lat, colfill, colborder, borderlwd, borderlty, ignorevisibility, removeidenticalneighbours, refineboundary, refineboundaryprecision))
}

slplotfieldloop <- function(plotinitres, num, lonv, latv, colbar, colbarbreaks, colfill = "black", colborder = "black", colbarbreakslog = FALSE, borderlwd = 0.01, borderlty = 1L) {
    invisible(.Call(spheRlab_slplotfieldloop, plotinitres, num, lonv, latv, colbar, colbarbreaks, colfill, colborder, colbarbreakslog, borderlwd, borderlty))
}

