# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sl.plot.polygon <- function(pir, lon, lat, polygon, colfill = "black", colborder = "black", borderlwd = 0.01, borderlty = 1L, ignorevisibility = FALSE, removeidenticalneighbours = TRUE, refineboundary = TRUE, refineboundaryprecision = 1) {
    invisible(.Call(`_spheRlab_slplotpolygon`, pir, lon, lat, polygon, colfill, colborder, borderlwd, borderlty, ignorevisibility, removeidenticalneighbours, refineboundary, refineboundaryprecision))
}

.sl.plot.field.loop <- function(plotinitres, lonv, latv, colbar, colind, colfill = "black", colborder = "black", borderlwd = 0.01, borderlty = 1L, threads = 1L) {
    invisible(.Call(`_spheRlab_slplotfieldloop`, plotinitres, lonv, latv, colbar, colind, colfill, colborder, borderlwd, borderlty, threads))
}

